# .opencode/workflow-template.yaml
# Kaizen PR Council — AUREA ➜ HERMES ➜ EVE ➜ JADE

version: 1
name: "Kaizen PR Council — AUREA ➜ HERMES ➜ EVE ➜ JADE"

triggers:
  # run on PR open/sync/comment: /council
  on:
    - pull_request.opened
    - pull_request.synchronize
    - pull_request.reopened
    - comment.command:/council

context:
  repo_paths:
    docs_index: "docs/README.md"
    config_units: "configs/integrity_units.yaml"
    units_pkg: "packages/integrity-units"
    ledger_svc: "services/civic-ledger"
  env:
    SHARDS_PER_CREDIT: "1000000"
  labels:
    needs-council: "council:pending"
    council-passed: "council:approved"
    council-blocked: "council:blocked"

flow:
  - id: aurea-architect
    agent: AUREA
    goal: >
      Structural & safety review. Verify changes keep economic math, configs,
      and service boundaries coherent. Flag breaking changes and missing docs.
    inputs:
      - diff
      - file:${context.repo_paths.config_units}
      - tree:${context.repo_paths.ledger_svc}
      - tree:${context.repo_paths.units_pkg}
    checks:
      required:
        - name: "Config is parsable"
          run: "yq '${.}' ${context.repo_paths.config_units} >/dev/null"
        - name: "Units TS builds"
          run: "pnpm -C ${context.repo_paths.units_pkg} build"
        - name: "Ledger service compiles"
          run: "pnpm -C ${context.repo_paths.ledger_svc} build"
    decision:
      pass_label: ${context.labels.needs-council}
      comment_style: pr_comment_style
      fail_hard: true   # stop flow if AUREA blocks

  - id: hermes-ops
    agent: HERMES
    goal: >
      Ops risk review. CI time, memory, and perf. Suggest concrete diffs.
    inputs:
      - diff
      - ci_logs
    checks:
      optional:
        - name: "Unit tests"
          run: "pnpm -C ${context.repo_paths.units_pkg} test || true"
        - name: "Smoke: ledger /health"
          run: "pnpm -C ${context.repo_paths.ledger_svc} dev & sleep 3 && curl -sf http://localhost:3000/health"
    decision:
      annotate_inline: true
      comment_style: pr_comment_style

  - id: eve-civic-audit
    agent: EVE
    goal: >
      Policy, licensing, accessibility, and human-readable docs.
      Ensure new endpoints & math are explained for non-engineers.
    inputs:
      - diff
      - file:${context.repo_paths.docs_index}
    actions:
      - when_missing:
          path: ${context.repo_paths.docs_index}
          create_file: |
            # Kaizen OS Documentation Index
            (autogenerated by EVE — please fill in details)
    decision:
      add_checklist: true
      comment_style: pr_comment_style

  - id: jade-morale
    agent: JADE
    goal: >
      Summarize intent in plain language, list possible confusions,
      and leave encouragement + next micro-step.
    inputs:
      - diff
      - thread
    decision:
      sticky_comment: true
      comment_style: pr_comment_style

quorum_rules:
  # AUREA has veto; otherwise council passes when 3/4 are non-blocking.
  hard_veto:
    - aurea-architect
  pass_when:
    any_of:
      - ids: [aurea-architect, hermes-ops, eve-civic-audit]
        min_success: 2

outcomes:
  on_pass:
    set_labels: [${context.labels.council-passed}]
    remove_labels: [${context.labels.needs-council}, ${context.labels.council-blocked}]
    comment: "✅ Council approves. Integrity flows steady."
  on_block:
    set_labels: [${context.labels.council-blocked}]
    remove_labels: [${context.labels.needs-council}, ${context.labels.council-passed}]
    comment: "🛑 Council blocked — see AUREA's notes above."
  on_pending:
    ensure_label: ${context.labels.needs-council}

commands:
  # Handy chat commands inside PR comments
  - name: "/council"
    description: "Re-run the Kaizen PR Council"
    run_flow: [aurea-architect, hermes-ops, eve-civic-audit, jade-morale]
  - name: "/aurea"
    run_flow: [aurea-architect]
  - name: "/hermes"
    run_flow: [hermes-ops]
  - name: "/eve"
    run_flow: [eve-civic-audit]
  - name: "/jade"
    run_flow: [jade-morale]
